#!/usr/bin/env python3
"""
Convert ``src/pdwidgets/icons/*.{pbm,bmp}`` into importable ``.py`` modules.

Installs ``pydisplay-graphics`` from TestPyPI (unless already importable), loads
each binary via ``FrameBuffer.from_file``, then writes a module matching the
graphics ``Font.export`` style (``WIDTH`` / ``HEIGHT`` / ``FORMAT`` / ``BITMAP``).

Usage (from the pdwidgets repo root)::

    .venv/bin/python scripts/assets_icons_to_py.py
    .venv/bin/python scripts/assets_icons_to_py.py --no-install   # use existing graphics
    .venv/bin/python scripts/assets_icons_to_py.py --delete-binaries

After conversion, runtime code loads ``pdwidgets.icons.<stem>`` modules (no
binary mip installs).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ICONS_DIR = REPO_ROOT / "src" / "pdwidgets" / "icons"
BINARY_SUFFIXES = {".pbm", ".bmp"}


def ensure_graphics(*, install: bool) -> None:
    try:
        import graphics  # noqa: F401

        return
    except ImportError:
        if not install:
            raise SystemExit(
                "graphics is not importable; omit --no-install or pip install "
                "pydisplay-graphics from TestPyPI"
            ) from None
    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-i",
        "https://test.pypi.org/simple/",
        "--extra-index-url",
        "https://pypi.org/simple/",
        "pydisplay-graphics",
    ]
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd)
    import graphics  # noqa: F401


def _bytes_literal_lines(data: bytes, width: int = 16) -> list[str]:
    lines: list[str] = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        lit = "".join(f"\\x{b:02x}" for b in chunk)
        cont = "\\" if i + width < len(data) else ""
        lines.append(f"b'{lit}'{cont}")
    return lines


def framebuffer_to_py(fb, dest: Path) -> None:
    """Write a FrameBuffer as an importable module (Font.export-style bytes)."""
    data = bytes(fb.buffer)
    lines = [
        "# Generated by scripts/assets_icons_to_py.py — do not edit by hand.",
        f"WIDTH = {int(fb.width)}",
        f"HEIGHT = {int(fb.height)}",
        f"FORMAT = {int(fb.format)}",
        "_BITMAP =\\",
    ]
    lines.extend(_bytes_literal_lines(data))
    lines.append("")
    lines.append("BITMAP = memoryview(_BITMAP)")
    lines.append("")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def convert_one(path: Path) -> Path:
    from graphics import FrameBuffer

    fb = FrameBuffer.from_file(str(path))
    out = path.with_suffix(".py")
    # graphics FrameBuffer.save() only writes pbm/pgm/bmp today: passing a
    # ``.py`` path appends ``.pbm``/``.bmp``. Emit Font.export-style modules.
    framebuffer_to_py(fb, out)
    return out


def verify_one(src_bin: Path, py_path: Path) -> None:
    from graphics import FrameBuffer

    orig = FrameBuffer.from_file(str(src_bin))
    # Import generated module by path without polluting package state permanently.
    import importlib.util

    spec = importlib.util.spec_from_file_location(py_path.stem, py_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {py_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    loaded = FrameBuffer(mod.BITMAP, mod.WIDTH, mod.HEIGHT, mod.FORMAT)
    if (loaded.width, loaded.height, loaded.format) != (orig.width, orig.height, orig.format):
        raise RuntimeError(
            f"{py_path.name}: meta mismatch "
            f"{(loaded.width, loaded.height, loaded.format)} vs "
            f"{(orig.width, orig.height, orig.format)}"
        )
    if bytes(loaded.buffer) != bytes(orig.buffer):
        raise RuntimeError(f"{py_path.name}: bitmap bytes differ from {src_bin.name}")


def ensure_package_init() -> None:
    init = ICONS_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            '# SPDX-FileCopyrightText: 2026 Brad Barnett\n#\n# SPDX-License-Identifier: MIT\n"""Importable icon modules for pdwidgets (generated .py bitmaps)."""\n',
            encoding="utf-8",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-install",
        action="store_true",
        help="Do not pip install pydisplay-graphics from TestPyPI",
    )
    parser.add_argument(
        "--delete-binaries",
        action="store_true",
        help="Delete source .pbm/.bmp after successful verify",
    )
    parser.add_argument(
        "--icons-dir",
        type=Path,
        default=ICONS_DIR,
        help=f"Icons directory (default: {ICONS_DIR})",
    )
    args = parser.parse_args()

    icons_dir: Path = args.icons_dir
    if not icons_dir.is_dir():
        raise SystemExit(f"Icons directory not found: {icons_dir}")

    ensure_graphics(install=not args.no_install)
    ensure_package_init()

    binaries = sorted(
        p for p in icons_dir.iterdir() if p.is_file() and p.suffix.lower() in BINARY_SUFFIXES
    )
    if not binaries:
        print(f"No .pbm/.bmp files in {icons_dir}")
        return 0

    converted = 0
    for src in binaries:
        out = convert_one(src)
        verify_one(src, out)
        print(f"  {src.name} -> {out.name} (ok)")
        converted += 1
        if args.delete_binaries:
            src.unlink()
            print(f"    deleted {src.name}")

    print(f"\nConverted {converted} icon(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
